/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.main.vista.reportes;

import batalla.main.dao.DAOBatalla;
import batalla.main.dao.DAOPersonaje;
import batalla.main.modelo.modeloBatallaBD;
import batalla.main.modelo.modeloPersonajeBD;
import java.util.List;

public class frmEstadisticas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmEstadisticas.class.getName());

    public frmEstadisticas() {
        initComponents();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                cargarEstadisticas();
            }
        });
    }
    
    private void cargarEstadisticas() {
        DAOPersonaje daoPersonaje = new DAOPersonaje();
        DAOBatalla daoBatalla = new DAOBatalla();       
        List<modeloPersonajeBD> todos = daoPersonaje.listarRanking();
        List<modeloBatallaBD> batallas = daoBatalla.listarHistorial(1000);       
        if (todos.isEmpty()) {
            jTextArea1.setText("ESTADISTICAS GENERALES\n\nNo hay datos disponibles");
            return;
        }      
        String texto = "";
        texto += "ESTADISTICAS GENERALES\n\n";
        int totalHeroes = 0;
        int totalVillanos = 0;
        int victoriasHeroes = 0;
        int victoriasVillanos = 0;
        int totalSupremos = 0;
        int batallaMasLarga = 0;
        modeloPersonajeBD mayorAtaque = null;
        
        for (modeloPersonajeBD p : todos) {
            if (p.getTipo().equals("Heroe")) {
                totalHeroes++;
                victoriasHeroes = victoriasHeroes + p.getVictorias();
            } else {
                totalVillanos++;
                victoriasVillanos = victoriasVillanos + p.getVictorias();
            }
            totalSupremos = totalSupremos + p.getSupremosUsados();
            
            if (mayorAtaque == null) {
                mayorAtaque = p;
            } else {
                if (p.getAtaque() > mayorAtaque.getAtaque()) {
                    mayorAtaque = p;
                }
            }
        }
        
        for (modeloBatallaBD b : batallas) {
            if (b.getTurnos() > batallaMasLarga) {
                batallaMasLarga = b.getTurnos();
            }
        }
        
        texto += "Total de Personajes: " + todos.size() + "\n";
        texto += "  - Heroes: " + totalHeroes + "\n";
        texto += "  - Villanos: " + totalVillanos + "\n";
        texto += "\n";
        texto += "Victorias por Tipo:\n";
        texto += "  - Heroes: " + victoriasHeroes + " victorias\n";
        texto += "  - Villanos: " + victoriasVillanos + " victorias\n";
        texto += "\n";
        
        if (mayorAtaque != null) {
            texto += "Mayor Ataque: " + mayorAtaque.getApodo() + " (" + mayorAtaque.getAtaque() + " puntos)\n";
        }
        texto += "\n";
        texto += "Total de Supremos Usados: " + totalSupremos + "\n";
        texto += "\n";
        
        if (batallaMasLarga > 0) {
            texto += "Batalla Mas Larga: " + batallaMasLarga + " turnos\n";
        }
        
        jTextArea1.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadisticas");
        setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {
        cargarEstadisticas();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmEstadisticas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
