/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.main.vista.reportes;

import batalla.main.dao.DAOBatalla;
import batalla.main.dao.DAOPersonaje;
import batalla.main.modelo.modeloBatallaBD;
import batalla.main.modelo.modeloPersonajeBD;
import java.util.List;

public class frmHistorial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHistorial.class.getName());

    public frmHistorial() {
        initComponents();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                cargarHistorial();
            }
        });
    }
    
    private void cargarHistorial() {
        DAOBatalla daoBatalla = new DAOBatalla();
        DAOPersonaje daoPersonaje = new DAOPersonaje();
        List<modeloBatallaBD> historial = daoBatalla.listarHistorial(10);
        
        if (historial.isEmpty()) {
            jTextArea1.setText("HISTORIAL DE BATALLAS\n\nNo hay batallas registradas");
            return;
        }
        
        String texto = "";
        texto += "HISTORIAL DE ULTIMAS 10 BATALLAS\n\n";
        
        int numero = 1;
        for (modeloBatallaBD batalla : historial) {
            modeloPersonajeBD heroe = daoPersonaje.buscarPorId(batalla.getHeroeId());
            modeloPersonajeBD villano = daoPersonaje.buscarPorId(batalla.getVillanoId());
            String nombreHeroe = "Desconocido";
            if (heroe != null) {
                nombreHeroe = heroe.getApodo();
            }
            String nombreVillano = "Desconocido";
            if (villano != null) {
                nombreVillano = villano.getApodo();
            }
            String ganador = "Sin ganador";
            if (batalla.getGanadorId() != null) {
                modeloPersonajeBD ganadorBD = daoPersonaje.buscarPorId(batalla.getGanadorId());
                if (ganadorBD != null) {
                    ganador = ganadorBD.getApodo();
                }
            }
            texto += "Batalla #" + numero + "\n";
            numero++;
            texto += "  Heroe: " + nombreHeroe + "\n";
            texto += "  Villano: " + nombreVillano + "\n";
            texto += "  Ganador: " + ganador + "\n";
            texto += "  Turnos: " + batalla.getTurnos() + "\n";
            texto += "\n";
        }
        
        jTextArea1.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial");
        setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setName("txtHistorial"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {
        cargarHistorial();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHistorial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
