/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.main.vista.reportes;

import batalla.main.dao.DAOPersonaje;
import batalla.main.modelo.modeloPersonajeBD;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class frmRanking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRanking.class.getName());

    public frmRanking() {
        initComponents();
        
        cargarRanking();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                cargarRanking();
            }
        });
    }
    
    private void cargarRanking() {
        try {
            DAOPersonaje daoPersonaje = new DAOPersonaje();
            List<modeloPersonajeBD> ranking = daoPersonaje.listarRanking();
            
            String[] columnas = {"Posicion", "Apodo", "Tipo", "Victorias", "Derrotas", "Ataque", "Defensa", "Vida Final"};
            DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            
            int posicion = 1;
            for (modeloPersonajeBD personaje : ranking) {
                Object[] fila = {
                    posicion++,
                    personaje.getApodo(),
                    personaje.getTipo(),
                    personaje.getVictorias(),
                    personaje.getDerrotas(),
                    personaje.getAtaque(),
                    personaje.getDefensa(),
                    personaje.getVidaFinal()
                };
                modelo.addRow(fila);
            }
            
            jTableRanking.setModel(modelo);
            
            if (jTableRanking.getColumnModel().getColumnCount() >= 8) {
                jTableRanking.getColumnModel().getColumn(0).setPreferredWidth(60);
                jTableRanking.getColumnModel().getColumn(1).setPreferredWidth(120);
                jTableRanking.getColumnModel().getColumn(2).setPreferredWidth(80);
                jTableRanking.getColumnModel().getColumn(3).setPreferredWidth(70);
                jTableRanking.getColumnModel().getColumn(4).setPreferredWidth(70);
                jTableRanking.getColumnModel().getColumn(5).setPreferredWidth(70);
                jTableRanking.getColumnModel().getColumn(6).setPreferredWidth(70);
                jTableRanking.getColumnModel().getColumn(7).setPreferredWidth(80);
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al cargar ranking", e);
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar el ranking: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRanking = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ranking De Personajes");
        setResizable(false);

        jScrollPane1.setName(""); // NOI18N

        jTableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRanking);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton1)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarRanking();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRanking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRanking;
    // End of variables declaration//GEN-END:variables
}
