/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.main.vista;
import batalla.main.controlador.controladorConfiguracion;
import javax.swing.SpinnerNumberModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.Random;
import batalla.main.modelo.Personaje;
import batalla.main.controlador.controladorBatalla;
import java.sql.SQLException;
import batalla.main.modelo.Heroe;
import batalla.main.modelo.Villano;

public class frmVistaConfiguracion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmVistaConfiguracion.class.getName());
        private Random random = new Random();
    controladorConfiguracion controlador = new controladorConfiguracion();
    public frmVistaConfiguracion() {
       initComponents();
    
    this.setSize(700, 500);
    this.setResizable(false);
    this.setLocationRelativeTo(null);
    

    controlador = new controladorConfiguracion();
    numVida.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
    numFuerza.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
    numDefensa.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
    numBendicion.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
    numVida.setValue(random.nextInt(61) + 100);
    numFuerza.setValue(random.nextInt(11) + 15);
    numDefensa.setValue(random.nextInt(6) + 8);
    numBendicion.setValue(random.nextInt(70) + 30);
   
    lsPersonajes.setModel(new DefaultListModel<>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtApodo = new javax.swing.JTextField();
        cbTipoPersonaje = new javax.swing.JComboBox<>();
        numFuerza = new javax.swing.JSpinner();
        numDefensa = new javax.swing.JSpinner();
        numBendicion = new javax.swing.JSpinner();
        btnAgregarPersonaje = new javax.swing.JButton();
        btnEliminarPersonaje = new javax.swing.JButton();
        numVida = new javax.swing.JSpinner();
        lblCantidadDeBatallas = new javax.swing.JLabel();
        cbCantidadBatallas = new javax.swing.JComboBox<>();
        chbActivarAtaqueSupremo = new javax.swing.JCheckBox();
        lblCantidadDeBatallas1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsPersonajes = new javax.swing.JList<>();
        btnIniciarBatalla = new javax.swing.JButton();
        btnCargarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion Inicial");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Configuracion Inicial");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel2.setText("Apodo :");

        jLabel3.setText("Tipo de Personaje :");

        jLabel4.setText("Vida :");

        jLabel5.setText("Fuerza :");

        jLabel6.setText("Defensa :");

        jLabel7.setText("Bendicion :");

        txtApodo.addActionListener(this::txtApodoActionPerformed);

        cbTipoPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heroe", "Villano" }));
        cbTipoPersonaje.addActionListener(this::cbTipoPersonajeActionPerformed);

        btnAgregarPersonaje.setLabel("Agregar Personaje");
        btnAgregarPersonaje.addActionListener(this::btnAgregarPersonajeActionPerformed);

        btnEliminarPersonaje.setLabel("Eliminar Personaje");
        btnEliminarPersonaje.addActionListener(this::btnEliminarPersonajeActionPerformed);

        lblCantidadDeBatallas.setText("Cantidad De Batallas :");

        cbCantidadBatallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbCantidadBatallas.addActionListener(this::cbCantidadBatallasActionPerformed);

        lblCantidadDeBatallas1.setText("Activar Ataque Supremo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(numBendicion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numVida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCantidadDeBatallas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCantidadBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCantidadDeBatallas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbActivarAtaqueSupremo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnAgregarPersonaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarPersonaje)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(numFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(numBendicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDeBatallas)
                    .addComponent(cbCantidadBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCantidadDeBatallas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarPersonaje)
                            .addComponent(btnEliminarPersonaje)))
                    .addComponent(chbActivarAtaqueSupremo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("lblApodo");
        jLabel3.getAccessibleContext().setAccessibleName("lblTipoPersonaje");
        jLabel4.getAccessibleContext().setAccessibleName("lblVida");
        jLabel5.getAccessibleContext().setAccessibleName("lblFuerza");
        jLabel6.getAccessibleContext().setAccessibleName("lblDefensa");
        jLabel7.getAccessibleContext().setAccessibleName("lblBendicion");
        txtApodo.getAccessibleContext().setAccessibleName("txtApodo");
        cbTipoPersonaje.getAccessibleContext().setAccessibleName("cbTipoPersonaje");
        numFuerza.getAccessibleContext().setAccessibleName("numFuerza");
        numDefensa.getAccessibleContext().setAccessibleName("numDefensa");
        numBendicion.getAccessibleContext().setAccessibleName("numBendicion");
        btnAgregarPersonaje.getAccessibleContext().setAccessibleName("btnAgregarPersonaje");
        btnEliminarPersonaje.getAccessibleContext().setAccessibleName("btnEliminarPersonaje");
        numVida.getAccessibleContext().setAccessibleName("numVida");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel8.setText("Personajes");

        jScrollPane2.setViewportView(lsPersonajes);
        lsPersonajes.getAccessibleContext().setAccessibleName("lsPersonajes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIniciarBatalla.setForeground(new java.awt.Color(0, 204, 51));
        btnIniciarBatalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batalla/main/vista/iconos/video.png"))); // NOI18N
        btnIniciarBatalla.setText("Iniciar Batalla");
        btnIniciarBatalla.addActionListener(this::btnIniciarBatallaActionPerformed);

        btnCargarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batalla/main/vista/iconos/reload.png"))); // NOI18N
        btnCargarPartida.setText("Cargar Partida");
        btnCargarPartida.addActionListener(this::btnCargarPartidaActionPerformed);

        btnSalir.setForeground(new java.awt.Color(255, 51, 51));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batalla/main/vista/iconos/logout.png"))); // NOI18N
        btnSalir.setLabel("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnIniciarBatalla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCargarPartida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarBatalla)
                    .addComponent(btnCargarPartida)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        btnIniciarBatalla.getAccessibleContext().setAccessibleName("btnIniciarBatalla");
        btnCargarPartida.getAccessibleContext().setAccessibleName("btnCargarPartida");
        btnSalir.getAccessibleContext().setAccessibleName("btnSalir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonajeActionPerformed
 try {
        String apodo = txtApodo.getText();
        String tipo = (String) cbTipoPersonaje.getSelectedItem();
        int vida = ((Number) numVida.getValue()).intValue();
        int fuerza = ((Number) numFuerza.getValue()).intValue();
        int defensa = ((Number) numDefensa.getValue()).intValue();
        int bendicion = ((Number) numBendicion.getValue()).intValue();
        
        controlador.agregarPersonaje(apodo, tipo, vida, fuerza, defensa, bendicion);
        
        actualizarListaPersonajes();
        
        txtApodo.setText("");
        numVida.setValue(random.nextInt(61) + 100);
        numFuerza.setValue(random.nextInt(11) + 15);
        numDefensa.setValue(random.nextInt(6) + 8);
        numBendicion.setValue(random.nextInt(70) + 30);
        

        String tipoSeleccionado = (String) cbTipoPersonaje.getSelectedItem();
        if (tipoSeleccionado.equals("Heroe")) {
            cbTipoPersonaje.setSelectedItem("Villano");
        } else {
            cbTipoPersonaje.setSelectedItem("Heroe");
        }
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage(),
            "Error de validacion",
            JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Error inesperado: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnAgregarPersonajeActionPerformed
private void actualizarListaPersonajes() {
      DefaultListModel<String> modelo = new DefaultListModel<>();
    if (controlador.tieneHeroe()) {
        modelo.addElement("Heroe: " + controlador.getHeroe().getApodo());
    }
    if (controlador.tieneVillano()) {
        modelo.addElement("Villano: " + controlador.getVillano().getApodo());
    }
    lsPersonajes.setModel(modelo);
}
    private void btnEliminarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonajeActionPerformed
    String seleccionado = lsPersonajes.getSelectedValue();
    if (seleccionado == null) {
        JOptionPane.showMessageDialog(
            this,
            "Selecciona un personaje para poder eliminarlo",
            "Aviso",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    
    int opcion = JOptionPane.showConfirmDialog(
        this,
        "?Estas Seguro que queres eliminar este personaje?",
        "Confirmar eliminacion",
        JOptionPane.YES_NO_OPTION
    );
    if (opcion == JOptionPane.YES_OPTION) {
        try {
            if (seleccionado.contains("Heroe")) {
                controlador.eliminarPersonaje("Heroe");
            } else if (seleccionado.contains("Villano")) {
                controlador.eliminarPersonaje("Villano");
            }
            
            actualizarListaPersonajes();
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    } 
    }//GEN-LAST:event_btnEliminarPersonajeActionPerformed

    private void btnIniciarBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarBatallaActionPerformed
        try {
        if (!controlador.personajesCompletos()) {
            JOptionPane.showMessageDialog(
                this,
                "Debes crear un Heroe y un Villano antes de iniciar la batalla.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        int cantidadBatallas = Integer.parseInt((String) cbCantidadBatallas.getSelectedItem());
        controlador.iniciarBatalla(cantidadBatallas);
        
        Heroe heroe = controlador.getHeroe();
        Villano villano = controlador.getVillano();
        
        this.setVisible(false);
        
        javax.swing.SwingUtilities.invokeLater(() -> {
            frmBatalla ventanaBatalla = new frmBatalla(heroe, villano, cantidadBatallas);
            ventanaBatalla.setVisible(true);
            ventanaBatalla.setLocationRelativeTo(null);
        });
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnIniciarBatallaActionPerformed

    private void cbCantidadBatallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCantidadBatallasActionPerformed

    }//GEN-LAST:event_cbCantidadBatallasActionPerformed

    private void btnCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPartidaActionPerformed
  try {
        Personaje[] personajes = controladorBatalla.cargarPartidaBD();
        
        if (personajes == null || personajes.length < 2) {
            JOptionPane.showMessageDialog(
                this,
                "No hay partidas guardadas en la base de datos.",
                "Informacion",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        // Convertir Personaje[] a Heroe y Villano
        Heroe heroe = (Heroe) personajes[0];
        Villano villano = (Villano) personajes[1];
        
        controlador.eliminarPersonaje("Heroe");
        controlador.eliminarPersonaje("Villano");
        
        controlador.agregarPersonaje(heroe.getApodo(), "Heroe", heroe.getVida(), heroe.getFuerza(), heroe.getDefensa(), heroe.getBendicion());
        controlador.agregarPersonaje(villano.getApodo(), "Villano", villano.getVida(), villano.getFuerza(), villano.getDefensa(), villano.getBendicion());
        
        actualizarListaPersonajes();
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "Partida cargada exitosamente.\n?Queres continuar la batalla?",
            "Partida Cargada",
            JOptionPane.YES_NO_OPTION
        );
        
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            
            javax.swing.SwingUtilities.invokeLater(() -> {
                frmBatalla ventanaBatalla = new frmBatalla(heroe, villano);
                ventanaBatalla.setVisible(true);
                ventanaBatalla.setLocationRelativeTo(null);
            });
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
            this,
            "Error al cargar la partida: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
        e.printStackTrace();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Error inesperado: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnCargarPartidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    int opcion = JOptionPane.showConfirmDialog(
        this,
        "?Estas seguro que queres salir?",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    if (opcion == JOptionPane.YES_OPTION) {
        controlador.salir();
        System.exit(0);
    }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbTipoPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPersonajeActionPerformed

    }//GEN-LAST:event_cbTipoPersonajeActionPerformed

    private void txtApodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApodoActionPerformed

    }//GEN-LAST:event_txtApodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmVistaConfiguracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersonaje;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JButton btnEliminarPersonaje;
    private javax.swing.JButton btnIniciarBatalla;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCantidadBatallas;
    private javax.swing.JComboBox<String> cbTipoPersonaje;
    private javax.swing.JCheckBox chbActivarAtaqueSupremo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidadDeBatallas;
    private javax.swing.JLabel lblCantidadDeBatallas1;
    private javax.swing.JList<String> lsPersonajes;
    private javax.swing.JSpinner numBendicion;
    private javax.swing.JSpinner numDefensa;
    private javax.swing.JSpinner numFuerza;
    private javax.swing.JSpinner numVida;
    private javax.swing.JTextField txtApodo;
    // End of variables declaration//GEN-END:variables
}
