/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.main.vista;
import javax.swing.SpinnerNumberModel;
import batalla.main.controlador.controladorConfiguracion;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author gaspi
 */
public class frmVistaConfiguracion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmVistaConfiguracion.class.getName());

    /**
     * Creates new form frmVistaConfiguracion
     */
    controladorConfiguracion controlador = new controladorConfiguracion();
    public frmVistaConfiguracion() {
        initComponents();
        this.setSize(650, 400);
        this.setResizable(false);
         numVida.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        numFuerza.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        numDefensa.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        numBendicion.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        
        Random random = new Random();
        numVida.setValue(random.nextInt(100, 161));
        numFuerza.setValue(random.nextInt(15, 26));
        numDefensa.setValue(random.nextInt(8, 14));
        numBendicion.setValue(random.nextInt(30, 100));
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtApodo = new javax.swing.JTextField();
        cbTipoPersonaje = new javax.swing.JComboBox<>();
        numFuerza = new javax.swing.JSpinner();
        numDefensa = new javax.swing.JSpinner();
        numBendicion = new javax.swing.JSpinner();
        btnAgregarPersonaje = new javax.swing.JButton();
        btnEliminarPersonaje = new javax.swing.JButton();
        numVida = new javax.swing.JSpinner();
        lblCantidadDeBatallas = new javax.swing.JLabel();
        cbCantidadBatallas = new javax.swing.JComboBox<>();
        chbActivarAtaqueSupremo = new javax.swing.JCheckBox();
        lblCantidadDeBatallas1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsPersonajes = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        btnIniciarBatalla = new javax.swing.JButton();
        btnCargarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Configuracion Inicial");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel2.setText("Apodo");

        jLabel3.setText("Tipo de Personaje");

        jLabel4.setText("Vida");

        jLabel5.setText("Fuerza");

        jLabel6.setText("Defensa");

        jLabel7.setText("Bendicion");

        cbTipoPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heroe ", "Villano", " " }));

        btnAgregarPersonaje.setLabel("Agregar Personaje");
        btnAgregarPersonaje.addActionListener(this::btnAgregarPersonajeActionPerformed);

        btnEliminarPersonaje.setLabel("Eliminar Personaje");
        btnEliminarPersonaje.addActionListener(this::btnEliminarPersonajeActionPerformed);

        lblCantidadDeBatallas.setText("Cantidad De Batallas");

        cbCantidadBatallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "5" }));
        cbCantidadBatallas.addActionListener(this::cbCantidadBatallasActionPerformed);

        lblCantidadDeBatallas1.setText("Activar Ataque Supremo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarPersonaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarPersonaje)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numVida, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numDefensa)
                                    .addComponent(numFuerza)
                                    .addComponent(txtApodo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipoPersonaje, javax.swing.GroupLayout.Alignment.LEADING, 0, 86, Short.MAX_VALUE)
                                    .addComponent(numBendicion, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantidadDeBatallas)
                                    .addComponent(lblCantidadDeBatallas1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCantidadBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(chbActivarAtaqueSupremo)
                                        .addGap(35, 35, 35)))))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cbTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(numVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(numDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(numBendicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCantidadBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadDeBatallas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbActivarAtaqueSupremo)
                    .addComponent(lblCantidadDeBatallas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPersonaje)
                    .addComponent(btnEliminarPersonaje))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("lblApodo");
        jLabel3.getAccessibleContext().setAccessibleName("lblTipoPersonaje");
        jLabel4.getAccessibleContext().setAccessibleName("lblVida");
        jLabel5.getAccessibleContext().setAccessibleName("lblFuerza");
        jLabel6.getAccessibleContext().setAccessibleName("lblDefensa");
        jLabel7.getAccessibleContext().setAccessibleName("lblBendicion");
        txtApodo.getAccessibleContext().setAccessibleName("txtApodo");
        cbTipoPersonaje.getAccessibleContext().setAccessibleName("cbTipoPersonaje");
        numFuerza.getAccessibleContext().setAccessibleName("numFuerza");
        numDefensa.getAccessibleContext().setAccessibleName("numDefensa");
        numBendicion.getAccessibleContext().setAccessibleName("numBendicion");
        btnAgregarPersonaje.getAccessibleContext().setAccessibleName("btnAgregarPersonaje");
        btnEliminarPersonaje.getAccessibleContext().setAccessibleName("btnEliminarPersonaje");
        numVida.getAccessibleContext().setAccessibleName("numVida");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lsPersonajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lsPersonajes);
        lsPersonajes.getAccessibleContext().setAccessibleName("lsPersonajes");

        jLabel8.setText("Personajes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIniciarBatalla.setText("Iniciar Batalla");
        btnIniciarBatalla.addActionListener(this::btnIniciarBatallaActionPerformed);

        btnCargarPartida.setText("Cargar Partida");
        btnCargarPartida.addActionListener(this::btnCargarPartidaActionPerformed);

        btnSalir.setLabel("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCargarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIniciarBatalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addGap(40, 40, 40))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciarBatalla)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarPartida)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnIniciarBatalla.getAccessibleContext().setAccessibleName("btnIniciarBatalla");
        btnCargarPartida.getAccessibleContext().setAccessibleName("btnCargarPartida");
        btnSalir.getAccessibleContext().setAccessibleName("btnSalir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonajeActionPerformed
String apodo = txtApodo.getText();
    String tipo = (String) cbTipoPersonaje.getSelectedItem();
    controlador.agregarPersonaje(apodo, tipo, 
        ((Number) numVida.getValue()).intValue(),
        ((Number) numFuerza.getValue()).intValue(),
        ((Number) numDefensa.getValue()).intValue(),
        ((Number) numBendicion.getValue()).intValue());
    txtApodo.setText("");
    
    // Actualizar la lista de personajes
    actualizarListaPersonajes();
}

// Método para actualizar la lista
private void actualizarListaPersonajes() {
    javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
    // Por ahora vacío, se completará en la siguiente etapa
    // modelo.addElement("Héroe: " + apodo);
    // modelo.addElement("Villano: " + apodo);
    lsPersonajes.setModel(modelo);
    }//GEN-LAST:event_btnAgregarPersonajeActionPerformed

    private void btnEliminarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonajeActionPerformed
        controlador.eliminarPersonaje(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPersonajeActionPerformed

    private void btnIniciarBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarBatallaActionPerformed
        int cantidadBatallas = Integer.parseInt((String) cbCantidadBatallas.getSelectedItem());
        controlador.iniciarBatalla(cantidadBatallas);        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarBatallaActionPerformed

    private void cbCantidadBatallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCantidadBatallasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCantidadBatallasActionPerformed

    private void btnCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPartidaActionPerformed
        controlador.cargarPartida();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarPartidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        controlador.salir();
    int opcion = JOptionPane.showConfirmDialog( this,
    "¿Está seguro que desea salir?",
    "Confirmar salida",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE
    );
    if (opcion == JOptionPane.YES_OPTION) {
    System.exit(0);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmVistaConfiguracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersonaje;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JButton btnEliminarPersonaje;
    private javax.swing.JButton btnIniciarBatalla;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCantidadBatallas;
    private javax.swing.JComboBox<String> cbTipoPersonaje;
    private javax.swing.JCheckBox chbActivarAtaqueSupremo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidadDeBatallas;
    private javax.swing.JLabel lblCantidadDeBatallas1;
    private javax.swing.JList<String> lsPersonajes;
    private javax.swing.JSpinner numBendicion;
    private javax.swing.JSpinner numDefensa;
    private javax.swing.JSpinner numFuerza;
    private javax.swing.JSpinner numVida;
    private javax.swing.JTextField txtApodo;
    // End of variables declaration//GEN-END:variables
}
